# Deploy latest commit to the server
- hosts: all
  roles:
    - common
  vars:
    HOST: '{{ inventory_hostname }}'
    PYTHON_VERSION: 'python3.8'
    WSGI_DIRECTORY: "<folder name where wsgi.py file is >"
    REPO_URL: "<git repository link here>"
    REPO_BRANCH: "<specify the branch name you want to clone>"
